### ISSUE TITLE
returnSpectators fails if gamemode is forced

### ISSUE THREAD

**Issue by n194** [totorewa/totos-carpet-tweaks#4]
If `force-gamemode=true` in server.properties, when the player logs off in spectator and logs on forced into survival mode, the player is not returned to their original position.

**Comment by totorewa** [comment]
Thanks for reporting this issue. It's not a scenario I had thought of. It took a little bit of time to think of how to solve this due to the server setting the player gamemode before they have spawned or even set the network handler, meaning teleportation wasn't available, but I've made it work.

Fix is included in release 0.2.2: https://github.com/totorewa/totos-carpet-tweaks/releases/tag/0.2.2
